service: serverless-playground

frameworkVersion: '3'

configValidationMode: error

plugins:
  - serverless-esbuild

params:
  default:
    appConfigAppId: ak00b6h
    appConfigEnvId: gbw62l2
    appConfigProfileId: oakibs7
    logRetentionInDays: 7
    tags:
      App: serverless.playground
      Env: ${sls:stage}
      OU: leanstacks
      Owner: Matthew Warman
  dev:
    profile: ls-dev
  qa:
    appConfigEnvId: v855leh
    profile: ls-qa
  prod:
    appConfigEnvId: nv960l4
    logRetentionInDays: 30
    profile: leanstacks

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 6
  logRetentionInDays: ${param:logRetentionInDays}
  tags: ${param:tags}
  stackTags: ${param:tags}
  layers:
    - arn:aws:lambda:us-east-1:027255383542:layer:AWS-AppConfig-Extension:128
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - appconfig:StartConfigurationSession
            - appconfig:GetLatestConfiguration
          Resource:
            - arn:aws:appconfig:${aws:region}:${aws:accountId}:application/${param:appConfigAppId}/environment/${param:appConfigEnvId}/configuration/*
  environment:
    AWS_APPCONFIG_APP_ID: ${param:appConfigAppId}
    AWS_APPCONFIG_ENV_ID: ${param:appConfigEnvId}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  findConfig:
    handler: src/handlers/config-find/index.handle
    events:
      - http:
          path: /configs/{configId}
          method: get
  findFlag:
    handler: src/handlers/flag-find/index.handle
    events:
      - http:
          path: /configs/{configId}/flags/{flagKey}
          method: get
  evaluateFlag:
    handler: src/handlers/flag-evaluate/index.handle
    events:
      - http:
          path: /configs/{configId}/flags/{flagKey}
          method: post

resources:
  Description: Serverless Framework Playground service component
