service: serverless-playground

frameworkVersion: '3'

configValidationMode: error

plugins:
  - serverless-esbuild

params:
  default:
    appConfigAppId: ak00b6h
    appConfigEnvId: gbw62l2
    appConfigProfileId: oakibs7
    appConfigFreeformProfileId: wmlda2c
    logRetentionInDays: 7
    origins: '*'
    tags:
      App: serverless.playground
      Env: ${sls:stage}
      OU: leanstacks
      Owner: Matthew Warman
  dev:
    profile: ls-dev
  qa:
    origins: '*'
    profile: ls-qa
  prod:
    logRetentionInDays: 30
    origins: '*'
    profile: leanstacks

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 6
  logRetentionInDays: ${param:logRetentionInDays}
  tags: ${param:tags}
  stackTags: ${param:tags}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - appconfig:StartConfigurationSession
            - appconfig:GetLatestConfiguration
          Resource:
            - arn:aws:appconfig:${aws:region}:${aws:accountId}:application/${param:appConfigAppId}/environment/${param:appConfigEnvId}/configuration/${param:appConfigProfileId}
            - arn:aws:appconfig:${aws:region}:${aws:accountId}:application/${param:appConfigAppId}/environment/${param:appConfigEnvId}/configuration/${param:appConfigFreeformProfileId}
  environment:
    ALLOW_ORIGIN: ${param:origins}
    AWS_APPCONFIG_APP_ID: ${param:appConfigAppId}
    AWS_APPCONFIG_ENV_ID: ${param:appConfigEnvId}
    AWS_APPCONFIG_PROFILE_ID: ${param:appConfigProfileId}
    AWS_APPCONFIG_FREEFORM_PROFILE_ID: ${param:appConfigFreeformProfileId}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  ping:
    handler: src/handlers/ping/index.handle
    layers:
      - arn:aws:lambda:us-east-1:027255383542:layer:AWS-AppConfig-Extension:128
    events:
      - http:
          path: /ping
          method: get
          cors:
            origin: ${param:origins}

resources:
  Description: Serverless Framework Playground service component
